INSERT INTO
    app.creators (
        platform,
        handle,
        url,
        lang,
        country,
        verified
    )
VALUES (
        'twitch',
        'ibai',
        'https://twitch.tv/ibai',
        'es',
        'ES',
        true
    ),
    (
        'twitch',
        'ernesbarbeq',
        'https://twitch.tv/ernesbarbeq',
        'es',
        'ES',
        true
    ),
    (
        'twitch',
        'tvander',
        'https://twitch.tv/tvander',
        'es',
        'ES',
        true
    ),
    (
        'twitch',
        'knekro',
        'https://twitch.tv/knekro',
        'es',
        'ES',
        true
    ),
    (
        'twitch',
        'rioboo',
        'https://twitch.tv/rioboo',
        'es',
        'ES',
        true
    ),
    (
        'twitch',
        'lakshartnia',
        'https://twitch.tv/lakshartnia',
        'es',
        'ES',
        true
    ),
    (
        'twitch',
        'mayichi',
        'https://twitch.tv/mayichi',
        'es',
        'ES',
        true
    ),
    (
        'twitch',
        'karchez',
        'https://twitch.tv/karchez',
        'es',
        'ES',
        true
    ),
    (
        'twitch',
        'blackelespanolito',
        'https://twitch.tv/blackelespanolito',
        'es',
        'ES',
        true
    ),
    (
        'twitch',
        'skain',
        'https://twitch.tv/skain',
        'es',
        'ES',
        true
    ),
    (
        'twitch',
        'sergiofferra',
        'https://twitch.tv/sergiofferra',
        'es',
        'ES',
        true
    ),
    (
        'twitch',
        'koi',
        'https://twitch.tv/koi',
        'es',
        'ES',
        true
    ) ON CONFLICT (platform, handle) DO NOTHING;