// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/hypemap/live": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "relay"
                ],
                "summary": "HypeMap: co-streams en vivo (ranking)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "val|lol",
                        "name": "game",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "es|en|fr|pt",
                        "name": "lang",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 50,
                        "description": "1-100",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "paginación",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/modules_relay_infra_http.HypeMapLiveResp"
                        }
                    }
                }
            }
        },
        "/v1/hypemap/summary": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "relay"
                ],
                "summary": "HypeMap: resumen por evento (agregado)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "val|lol",
                        "name": "game",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "es|en|fr|pt",
                        "name": "lang",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "1-100",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "paginación",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/modules_relay_infra_http.HypeMapSummaryResp"
                        }
                    }
                }
            }
        },
        "/v1/ingest/relay/costreams:upsert": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "ingest"
                ],
                "summary": "Ingest: upsert co-stream",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/modules_relay_infra_http.upsertCoStreamReq"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "no content"
                    },
                    "400": {
                        "description": "bad json",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "db error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/ingest/signal/comps:upsert": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "ingest"
                ],
                "summary": "Upsert de composición (ingesta)",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/modules_signal_infra_http.upsertCompReq"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "no content"
                    },
                    "400": {
                        "description": "bad json",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "db error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/relay/costreams": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "relay"
                ],
                "summary": "Listar co-streams en vivo de un evento",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug o ID del evento (ej. vct-emea-final)",
                        "name": "event_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filtro por idioma (ej. es)",
                        "name": "lang",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/modules_relay_infra_http.CoStreamsResp"
                        }
                    },
                    "400": {
                        "description": "event_id required",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/signal/changes": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "signal"
                ],
                "summary": "Listar cambios de un parche",
                "parameters": [
                    {
                        "enum": [
                            "lol",
                            "val"
                        ],
                        "type": "string",
                        "description": "lol | val",
                        "name": "game",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ej: 14.14 | 9.15",
                        "name": "version",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "agent",
                            "champion",
                            "item",
                            "weapon",
                            "map"
                        ],
                        "type": "string",
                        "description": "agent|champion|item|weapon|map",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/modules_signal_infra_http.ChangesResp"
                        }
                    },
                    "400": {
                        "description": "game and version required",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/signal/comps": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "signal"
                ],
                "summary": "Listar composiciones (LoL/VAL) filtradas",
                "parameters": [
                    {
                        "enum": [
                            "lol",
                            "val"
                        ],
                        "type": "string",
                        "description": "lol | val",
                        "name": "game",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "EMEA",
                        "name": "region",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "LEC",
                        "name": "league",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "14.14 | 9.15",
                        "name": "patch",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ascent (solo VAL)",
                        "name": "map",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "blue",
                            "red",
                            "attack",
                            "defense"
                        ],
                        "type": "string",
                        "description": "LoL: blue/red | VAL: attack/defense",
                        "name": "side",
                        "in": "query"
                    },
                    {
                        "maximum": 200,
                        "minimum": 1,
                        "type": "integer",
                        "default": 50,
                        "description": "1-100",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/modules_signal_infra_http.CompsResp"
                        }
                    },
                    "400": {
                        "description": "game, region and patch required",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/signal/leagues": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "signal"
                ],
                "summary": "Listar ligas por juego y región",
                "parameters": [
                    {
                        "enum": [
                            "lol",
                            "val"
                        ],
                        "type": "string",
                        "description": "lol | val",
                        "name": "game",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "EMEA",
                            "APAC",
                            "AMERICAS"
                        ],
                        "type": "string",
                        "description": "EMEA | APAC | AMERICAS",
                        "name": "region",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/modules_signal_infra_http.LeaguesResp"
                        }
                    },
                    "400": {
                        "description": "game required",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/signal/patches": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "signal"
                ],
                "summary": "Listar parches por juego",
                "parameters": [
                    {
                        "enum": [
                            "lol",
                            "val"
                        ],
                        "type": "string",
                        "description": "lol | val",
                        "name": "game",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/modules_signal_infra_http.PatchesResp"
                        }
                    },
                    "400": {
                        "description": "game required",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/signal/riot/champion-stats/{version}": {
            "get": {
                "description": "Retrieve detailed statistics about champion usage, pick rates, and performance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "riot"
                ],
                "summary": "Get champion statistics for a game version",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game version (e.g., 13.24.1)",
                        "name": "version",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Champion statistics",
                        "schema": {
                            "$ref": "#/definitions/modules_signal_infra_http.ChampionStatsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/signal/riot/games": {
            "get": {
                "description": "Retrieve list of all available games from Riot Games",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "riot"
                ],
                "summary": "Get available Riot Games",
                "responses": {
                    "200": {
                        "description": "List of available games",
                        "schema": {
                            "$ref": "#/definitions/modules_signal_infra_http.GamesResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/signal/riot/leagues/{platform}": {
            "get": {
                "description": "Retrieve list of all available leagues for a specific platform",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "riot"
                ],
                "summary": "Get available leagues for a platform",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Platform (e.g., na1, euw1, kr)",
                        "name": "platform",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of available leagues",
                        "schema": {
                            "$ref": "#/definitions/modules_signal_infra_http.LeaguesResponse"
                        }
                    },
                    "400": {
                        "description": "Platform parameter is required",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/signal/riot/metagame/league/{platform}/{queue}": {
            "get": {
                "description": "Get detailed analysis of Challenger league including win rates, LP distribution, and player statistics",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "riot"
                ],
                "summary": "Analyze league rankings and statistics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Platform (e.g., na1, euw1, kr)",
                        "name": "platform",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Queue type (e.g., RANKED_SOLO_5x5, RANKED_FLEX_SR)",
                        "name": "queue",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "League analysis with statistics and rankings",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Platform and queue parameters are required",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/signal/riot/metagame/report/{platform}": {
            "get": {
                "description": "Get complete meta-game analysis combining champion rotation and league statistics with insights and recommendations",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "riot"
                ],
                "summary": "Generate comprehensive meta-game report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Platform (e.g., na1, euw1, kr)",
                        "name": "platform",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Complete meta-game report with analysis and insights",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Platform parameter is required",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/signal/riot/metagame/rotation/{platform}": {
            "get": {
                "description": "Get detailed analysis of free champion rotation including tier classification, pick rates, and strategic recommendations",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "riot"
                ],
                "summary": "Analyze weekly champion rotation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Platform (e.g., na1, euw1, kr)",
                        "name": "platform",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Analysis result with champion data and recommendations",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Platform parameter is required",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/signal/riot/patch-changes/{fromVersion}/{toVersion}": {
            "get": {
                "description": "Compare changes between two game versions including buffs, nerfs, and new features",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "riot"
                ],
                "summary": "Get patch changes between versions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "From version (e.g., 13.23.1)",
                        "name": "fromVersion",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "To version (e.g., 13.24.1)",
                        "name": "toVersion",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Patch changes comparison",
                        "schema": {
                            "$ref": "#/definitions/modules_signal_infra_http.PatchChangesResponse"
                        }
                    },
                    "400": {
                        "description": "Version parameters are required",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/signal/riot/patches/{version}": {
            "get": {
                "description": "Retrieve detailed information about a specific game patch",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "riot"
                ],
                "summary": "Get detailed patch information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Patch version (e.g., 13.24.1)",
                        "name": "version",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Patch information",
                        "schema": {
                            "$ref": "#/definitions/modules_signal_infra_http.PatchInfoResponse"
                        }
                    },
                    "400": {
                        "description": "Version parameter is required",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Patch not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/signal/riot/pro-leagues": {
            "get": {
                "description": "Retrieve detailed information about all major professional leagues (LEC, LCK, LPL, etc.)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "riot"
                ],
                "summary": "Get professional League of Legends leagues information",
                "responses": {
                    "200": {
                        "description": "Professional leagues information",
                        "schema": {
                            "$ref": "#/definitions/modules_signal_infra_http.ProfessionalLeaguesResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/signal/riot/pro-leagues/{league}/champions": {
            "get": {
                "description": "Retrieve detailed champion statistics including pick rates, win rates, and ban rates for a specific professional league",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "riot"
                ],
                "summary": "Get champion statistics for a professional league",
                "parameters": [
                    {
                        "type": "string",
                        "description": "League code (e.g., LEC, LCK, LPL, LTA)",
                        "name": "league",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "League champion statistics",
                        "schema": {
                            "$ref": "#/definitions/modules_signal_infra_http.LeagueChampionsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid league parameter",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/signal/riot/regions": {
            "get": {
                "description": "Retrieve list of all available regions for League of Legends",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "riot"
                ],
                "summary": "Get available League of Legends regions",
                "responses": {
                    "200": {
                        "description": "List of available regions",
                        "schema": {
                            "$ref": "#/definitions/modules_signal_infra_http.RegionsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/signal/riot/sync/patches": {
            "post": {
                "description": "Sync latest patch information from Riot Games Data Dragon API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "riot"
                ],
                "summary": "Synchronize game patches from Riot Games",
                "responses": {
                    "200": {
                        "description": "Synchronization result",
                        "schema": {
                            "$ref": "#/definitions/modules_signal_infra_http.SyncPatchesResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_steven230500_hypeatlas-api_domain_entities.CoStream": {
            "type": "object",
            "properties": {
                "country": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "creator": {
                    "$ref": "#/definitions/github_com_steven230500_hypeatlas-api_domain_entities.Creator"
                },
                "creator_uuid": {
                    "type": "string"
                },
                "event": {
                    "$ref": "#/definitions/github_com_steven230500_hypeatlas-api_domain_entities.Event"
                },
                "event_uuid": {
                    "type": "string"
                },
                "is_live": {
                    "type": "boolean"
                },
                "lang": {
                    "type": "string"
                },
                "last_seen_at": {
                    "type": "string"
                },
                "platform": {
                    "description": "twitch|youtube",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                },
                "verified": {
                    "type": "boolean"
                },
                "viewers": {
                    "type": "integer"
                }
            }
        },
        "github_com_steven230500_hypeatlas-api_domain_entities.Comp": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "delta_win": {
                    "type": "number"
                },
                "game": {
                    "type": "string"
                },
                "league": {
                    "type": "string"
                },
                "map": {
                    "type": "string"
                },
                "patch": {
                    "type": "string"
                },
                "pick_rate": {
                    "type": "number"
                },
                "region": {
                    "type": "string"
                },
                "side": {
                    "type": "string"
                },
                "slots": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                },
                "win_rate": {
                    "type": "number"
                }
            }
        },
        "github_com_steven230500_hypeatlas-api_domain_entities.Creator": {
            "type": "object",
            "properties": {
                "country": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "handle": {
                    "type": "string"
                },
                "lang": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                },
                "verified": {
                    "type": "boolean"
                }
            }
        },
        "github_com_steven230500_hypeatlas-api_domain_entities.Event": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "ends_at": {
                    "type": "string"
                },
                "game": {
                    "description": "val|lol",
                    "type": "string"
                },
                "league": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "starts_at": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "github_com_steven230500_hypeatlas-api_domain_entities.HypeMapItem": {
            "type": "object",
            "properties": {
                "country": {
                    "type": "string"
                },
                "event_slug": {
                    "type": "string"
                },
                "event_title": {
                    "type": "string"
                },
                "game": {
                    "type": "string"
                },
                "handle": {
                    "type": "string"
                },
                "is_live": {
                    "type": "boolean"
                },
                "lang": {
                    "type": "string"
                },
                "league": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                },
                "viewers": {
                    "type": "integer"
                }
            }
        },
        "github_com_steven230500_hypeatlas-api_domain_entities.HypeMapSummaryItem": {
            "type": "object",
            "properties": {
                "event_slug": {
                    "type": "string"
                },
                "event_title": {
                    "type": "string"
                },
                "game": {
                    "type": "string"
                },
                "last_seen_at": {
                    "type": "string"
                },
                "league": {
                    "type": "string"
                },
                "streamers": {
                    "type": "integer"
                },
                "total_viewers": {
                    "type": "integer"
                }
            }
        },
        "github_com_steven230500_hypeatlas-api_domain_entities.League": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "game": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "github_com_steven230500_hypeatlas-api_domain_entities.Patch": {
            "type": "object",
            "properties": {
                "changes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_steven230500_hypeatlas-api_domain_entities.PatchChange"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "game": {
                    "description": "val|lol",
                    "type": "string"
                },
                "released_at": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "github_com_steven230500_hypeatlas-api_domain_entities.PatchChange": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "entity_id": {
                    "type": "string"
                },
                "entity_type": {
                    "description": "champion|agent|item|weapon|map",
                    "type": "string"
                },
                "field": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "impact_score": {
                    "type": "number"
                },
                "new": {
                    "type": "string"
                },
                "old": {
                    "type": "string"
                },
                "patch_uuid": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "modules_relay_infra_http.CoStreamsResp": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_steven230500_hypeatlas-api_domain_entities.CoStream"
                    }
                }
            }
        },
        "modules_relay_infra_http.HypeMapLiveResp": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_steven230500_hypeatlas-api_domain_entities.HypeMapItem"
                    }
                },
                "next_offset": {
                    "type": "integer"
                }
            }
        },
        "modules_relay_infra_http.HypeMapSummaryResp": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_steven230500_hypeatlas-api_domain_entities.HypeMapSummaryItem"
                    }
                },
                "next_offset": {
                    "type": "integer"
                }
            }
        },
        "modules_relay_infra_http.upsertCoStreamReq": {
            "type": "object",
            "properties": {
                "country": {
                    "type": "string"
                },
                "event_slug": {
                    "type": "string"
                },
                "event_title": {
                    "type": "string"
                },
                "game": {
                    "type": "string"
                },
                "handle": {
                    "type": "string"
                },
                "is_live": {
                    "type": "boolean"
                },
                "lang": {
                    "type": "string"
                },
                "league": {
                    "type": "string"
                },
                "platform": {
                    "description": "twitch|youtube",
                    "type": "string"
                },
                "starts_at": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "verified": {
                    "type": "boolean"
                },
                "viewers": {
                    "type": "integer"
                }
            }
        },
        "modules_signal_infra_http.ChampionStatsResponse": {
            "type": "object",
            "properties": {
                "stats": {
                    "type": "object",
                    "additionalProperties": true
                },
                "success": {
                    "type": "boolean"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "modules_signal_infra_http.ChangesResp": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_steven230500_hypeatlas-api_domain_entities.PatchChange"
                    }
                }
            }
        },
        "modules_signal_infra_http.CompsResp": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_steven230500_hypeatlas-api_domain_entities.Comp"
                    }
                }
            }
        },
        "modules_signal_infra_http.GamesResponse": {
            "type": "object",
            "properties": {
                "games": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "modules_signal_infra_http.LeagueChampionsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "additionalProperties": true
                },
                "league": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "modules_signal_infra_http.LeaguesResp": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_steven230500_hypeatlas-api_domain_entities.League"
                    }
                }
            }
        },
        "modules_signal_infra_http.LeaguesResponse": {
            "type": "object",
            "properties": {
                "leagues": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "platform": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "modules_signal_infra_http.PatchChangesResponse": {
            "type": "object",
            "properties": {
                "changes": {
                    "type": "object",
                    "additionalProperties": true
                },
                "from_version": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "to_version": {
                    "type": "string"
                }
            }
        },
        "modules_signal_infra_http.PatchInfoResponse": {
            "type": "object",
            "properties": {
                "patch": {
                    "$ref": "#/definitions/github_com_steven230500_hypeatlas-api_domain_entities.Patch"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "modules_signal_infra_http.PatchesResp": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_steven230500_hypeatlas-api_domain_entities.Patch"
                    }
                }
            }
        },
        "modules_signal_infra_http.ProfessionalLeaguesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "additionalProperties": true
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "modules_signal_infra_http.RegionsResponse": {
            "type": "object",
            "properties": {
                "regions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "modules_signal_infra_http.SyncPatchesResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "modules_signal_infra_http.upsertCompReq": {
            "type": "object",
            "properties": {
                "delta_win": {
                    "type": "number"
                },
                "game": {
                    "type": "string"
                },
                "league": {
                    "type": "string"
                },
                "map": {
                    "type": "string"
                },
                "patch": {
                    "type": "string"
                },
                "pick_rate": {
                    "type": "number"
                },
                "region": {
                    "type": "string"
                },
                "side": {
                    "type": "string"
                },
                "slots": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "win_rate": {
                    "type": "number"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "api.hypeatlas.app",
	BasePath:         "/",
	Schemes:          []string{"https", "http"},
	Title:            "HypeAtlas API",
	Description:      "Relay (HypeMap), Signal (MetaLens) y Comps & Leagues.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
