  /v1/signal/leagues:
    get:
      parameters:
        - in: query
          name: game
          required: true
          schema: { type: string }
        - in: query
          name: region
          schema: { type: string }
      responses: { '200': { description: OK } }

  /v1/signal/comps:
    get:
      parameters:
        - in: query
          name: game
          required: true
          schema: { type: string }
        - in: query
          name: region
          required: true
          schema: { type: string }
        - in: query
          name: league
          schema: { type: string }
        - in: query
          name: patch
          required: true
          schema: { type: string }
        - in: query
          name: map
          schema: { type: string }
        - in: query
          name: side
          schema: { type: string }
        - in: query
          name: limit
          schema: { type: integer, default: 50 }
      responses: { '200': { description: OK } }
